### ISSUE TITLE
Buggy with for...in

### ISSUE THREAD

**Issue by yukulele** [jameswestgate/JavaScript-1.6-Polyfill#1]
Their is a bug with this polyfill when explore array with `for...in`
exemple:

``` javascript
for(k in ['a','b','c']){
    console.log(k) 
}
```

without js1.6 polyfill

```
0 
1 
2 
```

with js1.6 polyfill

```
0
1
2
indexOf 
lastIndexOf 
every 
filter 
forEach 
map 
some 
```

**Comment by jameswestgate** [comment]
Looks like this is missing a bit of _ hasOwnProperty_. Not sure what the required functionality would be _for (key in value)_ output for arrays vs object literals {a: 1, b:2, c:3}
